/*
 * AbstractArrowtoothAttributesCustomizer.java
 */

package wts.models.DisMELS.IBMs.ArrowtoothFlounder;

import wts.models.DisMELS.framework.*;
import wts.models.DisMELS.gui.AttributesCustomizer;

/**
 * Customizer for AbstractArrowtoothAttributes classes.
 */
public class AbstractArrowtoothAttributesCustomizer extends AttributesCustomizer {

    private AbstractArrowtoothAttributes attributes = null;
    
    /**
     * Creates new customizer
     */
    public AbstractArrowtoothAttributesCustomizer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        czrStandardAttributes = new wts.models.DisMELS.gui.AbstractLHSAttributesCustomizer();
        jPanel2 = new javax.swing.JPanel();
        jcbAttached = new javax.swing.JCheckBox();
        jtfSize = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfWeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(czrStandardAttributes, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional attributes"));

        jcbAttached.setText("attached?");
        jcbAttached.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAttachedActionPerformed(evt);
            }
        });

        jtfSize.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfSize.setText("0");
        jtfSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSizeActionPerformed(evt);
            }
        });

        jLabel1.setText("Size (mm)");

        jtfWeight.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfWeight.setText("0");
        jtfWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfWeightActionPerformed(evt);
            }
        });

        jLabel2.setText("Weight (g)");
        jLabel2.setToolTipText("");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfWeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jcbAttached)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jcbAttached)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfWeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSizeActionPerformed
        Double n = new Double(jtfSize.getText());
        attributes.setValue(attributes.PROP_size,n);
    }//GEN-LAST:event_jtfSizeActionPerformed

    private void jtfWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfWeightActionPerformed
        Double n = new Double(jtfWeight.getText());
        attributes.setValue(attributes.PROP_weight,n);
    }//GEN-LAST:event_jtfWeightActionPerformed

    private void jcbAttachedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAttachedActionPerformed
        Boolean b = new Boolean(jcbAttached.isSelected());
        attributes.setValue(attributes.PROP_attached,b);
    }//GEN-LAST:event_jcbAttachedActionPerformed

    @Override
    public void setObject(Object bean) {
        if (bean instanceof AbstractArrowtoothAttributes) {
            setAttributes((AbstractArrowtoothAttributes) bean);
        }
    }
    
    @Override
    public AbstractArrowtoothAttributes getAttributes() {
        return attributes;
    }
    
    @Override
    public void setAttributes(LifeStageAttributesInterface newAtts) {
        if (newAtts instanceof AbstractArrowtoothAttributes) {
            attributes = (AbstractArrowtoothAttributes) newAtts;
            czrStandardAttributes.setObject(attributes);
            Boolean b = null;
            jcbAttached.setSelected(attributes.getValue(attributes.PROP_attached,b).booleanValue());
            Double d = null;
            jtfSize.setText(attributes.getValue(attributes.PROP_size,d).toString());
            jtfWeight.setText(attributes.getValue(attributes.PROP_weight,d).toString());
        }
    }
    
    @Override
    public void showHorizPos(boolean b) {
        czrStandardAttributes.showHorizPos(b);
        revalidate();
    }
    
    @Override
    public void showVertPos(boolean b) {
        czrStandardAttributes.showVertPos(b);
        revalidate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private wts.models.DisMELS.gui.AbstractLHSAttributesCustomizer czrStandardAttributes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcbAttached;
    private javax.swing.JTextField jtfSize;
    private javax.swing.JTextField jtfWeight;
    // End of variables declaration//GEN-END:variables
    
}
